# Config file for automatic testing at travis-ci.com

language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.8
      env: TOXENV=py38
    - python: 3.8
      env: TOXENV=quality
    - python: 3.8
      env: TOXENV=docs

cache:
  - pip

before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements/travis.txt

script:
  - tox

before_deploy:
  # The quality step makes an sdist, but its presence prevents deploy.
  - rm -rf src/scriv.egg-info dist

deploy:
  provider: pypi
  user: "__token__"
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: '$TOXENV = quality'
  password:
    secure: XQwBsoXBym5zI64/AxElKAotz/PI/jnzEJvsfEoK7tsym31aI1VTRMerVpC64TABCf8YceOAcvIWIDobWCRBpo7biqTWJAmX2w6cC8QI7+Oic6vO0oU5PGO5QLHa2zDGpkqjiGwcvjBY7UddTKAdIv9KiNqD/5cRgfG4lT5uzKpJhVOranWmlyUv5AQOULfYlzxGT/sEc3hxUKvCvcLjXc/3PNVurMTOUOMd1YtoYaQas+onbh2jVxG0ey6ZHhO0Q1OIyxuI3SrtBS9bCatwmliZSwGQy6+Ucy9FZPeLdZUQR8VJp5ZUN18V4BJ1QEkait7IDtrGwkxUV91R2dZ/4kjiOhKO2D+sBlR/yEWXslXXbgIo4fa+KPL8gUn/WQrNYCB1iauhhnCBZ5GB1mamXEx8X7uDn9ekw6P76FsjVt6GWWKyHbuhlTg5gRZPQUPyuEbJ0u/5XJECHb2rCvluUqoboIinRcgVWr4fYBBDEi9iLZ5kSjw8T0Z+SL00J7/SzrPp/2j1Ma2O+ECRRwsGEJjkO2hqXP+LT3/aM+Y3wBMGnhwOhFFPptS2+PZFU1zuDE42YqAtL49/9rZoU5IPv4nSMjwLShNJlKRWfky7IpLv2AmRNPi7wxfoi7r7jFPKk33WXUt7ik7aQ93YRbWwD/1WJIXblesfEOn3y6SyIfA=
